services:
  - type: web
    name: Brijeshbhattarai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: ADMIN_EMAIL
        value: brijeshbh78901@gmail.com
